# Generated by Django 6.0.4 on 2026-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
